### ISSUE TITLE
Alternative time units

### ISSUE THREAD

**Issue by jcristovao** [basvandijk/unbounded-delays#3]
Hi,
I've been using [Richard Einsenberg](http://www.cis.upenn.edu/~eir/)s [units](https://hackage.haskell.org/package/units) and [units-defs](https://hackage.haskell.org/package/units-defs) with great success.

Being a fan of unbounded-delays, I even [ended-up](http://fundeps.com/posts/haskell/2014-05-24-An-Experiment-with-Typed-Time/) doing a [version of my own](https://github.com/jcristovao/unbounded-delays-units).

But of course, this means then also having to do custom version of [stm-extras](https://hackage.haskell.org/package/concurrent-extra), and so on.

Would you consider merging this into unbouded delays? Or would the extra dependencies (Singletons, and hence Template Haskell) be to much of a burden?

A possible alternative would be to define Time as a typeclass, that could either be Integer (the instance defined here) or [Time](https://hackage.haskell.org/package/units-defs-1.0.1/docs/Data-Metrology-SI-Dims.html#t:Time).

What do you think?
Thanks
João

**Comment by jcristovao** [comment]
Ok :)

Nevertheless, would it be too much to ask for a link to my wrapper package on the Readme and/or Haddock docs, for those interested? I can do the pull request...

Thanks

**Comment by basvandijk** [comment]
> Nevertheless, would it be too much to ask for a link to my wrapper package on the Readme and/or Haddock docs, for those interested? I can do the pull request...

No problem.
