### ISSUE TITLE
Build-Type: Custom vs cross-compilation

### ISSUE THREAD

**Issue by BartMassey** [basvandijk/unbounded-delays#9]
Unfortunately, because of GHC bug [#1493](https://github.com/haskell/cabal/issues/1493), it is currently not possible to build unbounded-delays with a cross-compiler out of the box: the Setup.hs is compiled using the target compiler rather than the host compiler. Changing the build type to Simple fixes this, and it looks like all the custom Setup.hs does is some Haddock magic. Any chance of getting Build-Type: Simple into a version on Hackage?

**Comment by ezyang** [comment]
Agreed, the custom Haddock preprocessor is *so not worth it*. Can it please be ejected?

**Comment by angerman** [comment]
This ticket is not almost 30mo old. Can we finally drop the custom build type?

I see that `#ifdef __HADDOCK__` is uses.  Can't this be substituted by `__HADDOCK_VERSION__`?
> Cabal also allows to detect when the source code is being used for
> generating documentation. The ``__HADDOCK_VERSION__`` macro is defined
> only when compiling via Haddock_
> instead of a normal Haskell compiler. The value of the
> ``__HADDOCK_VERSION__`` macro is defined as ``A*1000 + B*10 + C``, where
> ``A.B.C`` is the Haddock version. This can be useful for working around
> bugs in Haddock or generating prettier documentation in some special
> cases.
(source: Conditional Compilation in the `developing-packages.rst`)

**Comment by BartMassey** [comment]
2.5 years unaddressed, and no resolution in sight. It's like we're experiencing an...

Naw. Can't do it.

**Comment by basvandijk** [comment]
Sorry for the almost unbounded delay in fixing this. Released as [unbounded-delays-0.1.1.0](http://hackage.haskell.org/package/unbounded-delays-0.1.1.0).

**Comment by BartMassey** [comment]
Thanks much!
